### ISSUE TITLE
not working on Mac x64

### ISSUE THREAD

**Issue by Jonham** [smack0007/deno-sdl2-ffi#22]
```shell
brew install sdl2 sdl2_image sdl2_ttf

dir_path=sdl
if [ ! -d "$dir_path" ]; then
    mkdir $dir_path
fi

projectPath=`pwd`
deno run --allow-net --allow-read="$projectPath" --allow-write="$projectPath" --import-map https://deno.land/x/sdl_ts@0.0.4/imports.deno.json https://deno.land/x/sdl_ts@0.0.4/init.ts "$projectPath"

sdl deno task start

// return
error: Uncaught (in promise) Error: Failed to load library "darwin/x64/libSDL2.a"
    throw new SDLError(`Failed to load library "${libraryPath}"`, error);
          ^
    at loadLibrary (https://deno.land/x/sdl_ts@0.0.4/src/deno/_library.ts:25:11)
    at Module.Init (https://deno.land/x/sdl_ts@0.0.4/src/SDL/functions.ts:330:14)
    at main (file:///Users/jonham/code/sdl2-deno/sdl/main.ts:4:7)
    at file:///Users/jonham/code/sdl2-deno/sdl/main.ts:38:11
Caused by: Error: Could not open library: Could not open library: dlopen(darwin/x64/libSDL2.a, 0x0005): tried: 'darwin/x64/libSDL2.a' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OSdarwin/x64/libSDL2.a' (no such file), '/usr/lib/darwin/x64/libSDL2.a' (no such file, not in dyld cache), 'darwin/x64/libSDL2.a' (not a mach-o file), '/Users/jonham/code/sdl2-deno/sdl/darwin/x64/libSDL2.a' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jonham/code/sdl2-deno/sdl/darwin/x64/libSDL2.a' (no such file), '/Users/jonham/code/sdl2-deno/sdl/darwin/x64/libSDL2.a' (not a mach-o file)
```

**Comment by Jonham** [comment]
I fetch this repo, and replaced `import { SDL } from "SDL_ts";` with `import { SDL } from "./SDL_ts/mod.ts";` in the `main.ts` created by init CLI, and also thrown an error.
But it can be fixed by copy `libSDL2.dylib` to the dir `main.ts` is in.
```shell
ln -s /usr/local/Cellar/sdl2/2.30.0/lib/libSDL2.dylib .
```
```

**Comment by Jonham** [comment]
resolved by https://github.com/smack0007/SDL_ts/pull/23
