### ISSUE TITLE
Error: Failed to load library "darwin/x64/libSDL2.a" on Apple Silicon 

### ISSUE THREAD

**Issue by brettchalupa** [smack0007/deno-sdl2-ffi#30]
I'm on an Apple M2 Pro chip, and I followed the Homebrew install instructions for the dependencies:

```
brew install sdl2 sdl2_image sdl2_ttf
```

And I created a new project from the init script. When I run `deno task start`, I get the following error:

```
error: Uncaught (in promise) Error: Failed to load library "darwin/x64/libSDL2.a"
    throw new SDLError(`Failed to load library "${libraryPath}"`, error);
          ^
    at loadLibrary (https://deno.land/x/sdl_ts@0.0.4/src/deno/_library.ts:25:11)
    at Module.Init (https://deno.land/x/sdl_ts@0.0.4/src/SDL/functions.ts:330:14)
    at main (file:///Users/brett/workspace/deno_learning/denosdl/main.ts:4:7)
    at file:///Users/brett/workspace/deno_learning/denosdl/main.ts:38:11
Caused by: Error: Could not open library: Could not open library: dlopen(darwin/x64/libSDL2.a, 0x0005): tried: 'darwin/x64/libSDL2.a' (no such file), '/System/Volumes/Preboot/Cryptexes/OSdarwin/x64/libSDL2.a' (no such file), '/usr/lib/darwin/x64/libSDL2.a' (no such file, not in dyld cache), 'darwin/x64/libSDL2.a' (no such file)
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:454:42)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:558:10)
    at loadLibrary (https://deno.land/x/sdl_ts@0.0.4/src/deno/_library.ts:23:17)
    at Module.Init (https://deno.land/x/sdl_ts@0.0.4/src/SDL/functions.ts:330:14)
    at main (file:///Users/brett/workspace/deno_learning/denosdl/main.ts:4:7)
    at file:///Users/brett/workspace/deno_learning/denosdl/main.ts:38:11
```

Happy to debug/share/investigate anything I can to help address this issue. Thanks for the project, I think it's really exciting!

## Version Details

- Homebrew 4.3.7
- MacOS 14.5
- sdl2 2.30.4

```
$ brew info sdl2
==> sdl2: stable 2.30.4 (bottled), HEAD
Low-level access to audio, keyboard, mouse, joystick, and graphics
https://www.libsdl.org/
Installed
/opt/homebrew/Cellar/sdl2/2.30.0 (93 files, 6.5MB)
  Poured from bottle using the formulae.brew.sh API on 2024-02-09 at 21:09:28
/opt/homebrew/Cellar/sdl2/2.30.2 (93 files, 6.5MB)
  Poured from bottle using the formulae.brew.sh API on 2024-04-11 at 09:21:15
/opt/homebrew/Cellar/sdl2/2.30.4 (94 files, 6.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-06-19 at 10:01:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/s/sdl2.rb
License: Zlib
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 62,397 (30 days), 198,583 (90 days), 652,567 (365 days)
install-on-request: 9,237 (30 days), 30,790 (90 days), 110,916 (365 days)
build-error: 2 (30 days)
```

**Comment by smack0007** [comment]
Hi the Logic for looking for the SDL Library is in `src/deno/_library.ts`. The code looks in `"/usr/local/lib"` and `"/System/Volumes/Data/opt/homebrew/lib"`. I haven't looked at the Mac Version in a while but it looks like according to your provided output that library is under "Cellar". I'm by no means a Homebrew expert so I have no idea why the path is different on your machine but I have no problem with a pull request where you add the new path.

**Comment by smack0007** [comment]
Took a look at my Mac this morning and my `brew info sdl2` looks similar:
```
# brew info sdl2
==> sdl2: stable 2.30.4 (bottled), HEAD
Low-level access to audio, keyboard, mouse, joystick, and graphics
https://www.libsdl.org/
Installed
/opt/homebrew/Cellar/sdl2/2.30.4 (94 files, 6.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-06-26 at 10:32:31
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/s/sdl2.rb
License: Zlib
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 63,382 (30 days), 199,464 (90 days), 650,261 (365 days)
install-on-request: 9,469 (30 days), 30,892 (90 days), 110,309 (365 days)
build-error: 2 (30 days)
```

Can you check and see if the symlinks exist in `/System/Volumes/Data/opt/homebrew/lib`?:
```
# ls /System/Volumes/Data/opt/homebrew/lib/libSDL*
/System/Volumes/Data/opt/homebrew/lib/libSDL2-2.0.0.dylib
/System/Volumes/Data/opt/homebrew/lib/libSDL2.a
/System/Volumes/Data/opt/homebrew/lib/libSDL2.dylib
/System/Volumes/Data/opt/homebrew/lib/libSDL2_image-2.0.0.dylib
/System/Volumes/Data/opt/homebrew/lib/libSDL2_image.a
/System/Volumes/Data/opt/homebrew/lib/libSDL2_image.dylib
/System/Volumes/Data/opt/homebrew/lib/libSDL2_test.a
/System/Volumes/Data/opt/homebrew/lib/libSDL2_ttf-2.0.0.dylib
/System/Volumes/Data/opt/homebrew/lib/libSDL2_ttf.a
/System/Volumes/Data/opt/homebrew/lib/libSDL2_ttf.dylib
/System/Volumes/Data/opt/homebrew/lib/libSDL2main.a
```

**Comment by smack0007** [comment]
Ah wait I see you are loading it through `deno.land`. That version is extremely old and I'm not even sure if it works anymore. I really need to update the Getting Started section of the Readme. Try cloning the source code via git and see if you have better results. I'll try and find the time to get the Readme updated.

**Comment by brettchalupa** [comment]
I got it working by using the library source from GitHub, thanks!

I cloned and added the reference to the library clone location:

```typescript
import { SDL } from "../SDL_ts/mod.ts";
```
